// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: protofiles/ping-pong.proto

package grpc_microservices_

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing requested numbers
type MathRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A int32 `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B int32 `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *MathRequest) Reset() {
	*x = MathRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_ping_pong_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MathRequest) ProtoMessage() {}

func (x *MathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_ping_pong_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MathRequest.ProtoReflect.Descriptor instead.
func (*MathRequest) Descriptor() ([]byte, []int) {
	return file_protofiles_ping_pong_proto_rawDescGZIP(), []int{0}
}

func (x *MathRequest) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *MathRequest) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

// The response message containing response
type MathReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *MathReply) Reset() {
	*x = MathReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_ping_pong_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MathReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MathReply) ProtoMessage() {}

func (x *MathReply) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_ping_pong_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MathReply.ProtoReflect.Descriptor instead.
func (*MathReply) Descriptor() ([]byte, []int) {
	return file_protofiles_ping_pong_proto_rawDescGZIP(), []int{1}
}

func (x *MathReply) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_protofiles_ping_pong_proto protoreflect.FileDescriptor

var file_protofiles_ping_pong_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x70, 0x69, 0x6e,
	0x67, 0x2d, 0x70, 0x6f, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6d, 0x61,
	0x74, 0x68, 0x74, 0x65, 0x73, 0x74, 0x22, 0x29, 0x0a, 0x0b, 0x4d, 0x61, 0x74, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x01, 0x61, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01,
	0x62, 0x22, 0x23, 0x0a, 0x09, 0x4d, 0x61, 0x74, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x47, 0x0a, 0x08, 0x4d, 0x61, 0x74, 0x68, 0x54, 0x65,
	0x73, 0x74, 0x12, 0x3b, 0x0a, 0x0b, 0x73, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x15, 0x2e, 0x6d, 0x61, 0x74, 0x68, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x61, 0x74,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x6d, 0x61, 0x74, 0x68, 0x74,
	0x65, 0x73, 0x74, 0x2e, 0x4d, 0x61, 0x74, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42,
	0x15, 0x5a, 0x13, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protofiles_ping_pong_proto_rawDescOnce sync.Once
	file_protofiles_ping_pong_proto_rawDescData = file_protofiles_ping_pong_proto_rawDesc
)

func file_protofiles_ping_pong_proto_rawDescGZIP() []byte {
	file_protofiles_ping_pong_proto_rawDescOnce.Do(func() {
		file_protofiles_ping_pong_proto_rawDescData = protoimpl.X.CompressGZIP(file_protofiles_ping_pong_proto_rawDescData)
	})
	return file_protofiles_ping_pong_proto_rawDescData
}

var file_protofiles_ping_pong_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protofiles_ping_pong_proto_goTypes = []interface{}{
	(*MathRequest)(nil), // 0: mathtest.MathRequest
	(*MathReply)(nil),   // 1: mathtest.MathReply
}
var file_protofiles_ping_pong_proto_depIdxs = []int32{
	0, // 0: mathtest.MathTest.sendRequest:input_type -> mathtest.MathRequest
	1, // 1: mathtest.MathTest.sendRequest:output_type -> mathtest.MathReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protofiles_ping_pong_proto_init() }
func file_protofiles_ping_pong_proto_init() {
	if File_protofiles_ping_pong_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protofiles_ping_pong_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MathRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_ping_pong_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MathReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protofiles_ping_pong_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protofiles_ping_pong_proto_goTypes,
		DependencyIndexes: file_protofiles_ping_pong_proto_depIdxs,
		MessageInfos:      file_protofiles_ping_pong_proto_msgTypes,
	}.Build()
	File_protofiles_ping_pong_proto = out.File
	file_protofiles_ping_pong_proto_rawDesc = nil
	file_protofiles_ping_pong_proto_goTypes = nil
	file_protofiles_ping_pong_proto_depIdxs = nil
}
