version: '3.1'

services:
  postgres-server:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGUSER: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5

  cpp_server_pingpong_mathtest:
    image: gcc:latest
    build:
      context: cpp_server_pingpong_mathtest
      build: Dockerfile

  go_client_pingpong_mathtest:
    image: golang:1.20
    

network:
  docker_network:
    name: internal_network